In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
titanic=sns.load_dataset("titanic")

In [3]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### Data Preprocessing

In [5]:
titanic.drop(["class","embark_town","deck","adult_male","who","alive","alone"],axis=1,inplace=True)

In [6]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
titanic.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [9]:
titanic["embarked"].fillna(method="ffill",inplace=True)

C:\Users\Predator\AppData\Local\Temp\ipykernel_1624\1649074084.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  titanic["embarked"].fillna(method="ffill",inplace=True)


In [10]:
titanic["age"].fillna(titanic.age.median(),inplace=True)

In [11]:
titanic.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [12]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [14]:
#Label Encoding embarked
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [16]:
titanic["embarked"]=label.fit_transform(titanic.embarked)

In [17]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare  embarked
0         0       3    male  22.0      1      0   7.2500         2
1         1       1  female  38.0      1      0  71.2833         0
2         1       3  female  26.0      0      0   7.9250         2
3         1       1  female  35.0      1      0  53.1000         2
4         0       3    male  35.0      0      0   8.0500         2

In [18]:
titanic["age"]=label.fit_transform(titanic.age)

In [21]:
titanic.sex=label.fit_transform(titanic.sex)

In [22]:
titanic.head()

survived  pclass  sex  age  sibsp  parch     fare  embarked
0         0       3    1   28      1      0   7.2500         2
1         1       1    0   51      1      0  71.2833         0
2         1       3    0   34      0      0   7.9250         2
3         1       1    0   47      1      0  53.1000         2
4         0       3    1   47      0      0   8.0500         2

In [23]:
titanic.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [55]:
X_train,X_test,y_train,y_test=train_test_split(titanic.drop("survived",axis=1),titanic.survived,test_size=0.3,random_state=100)

In [56]:
X_train.shape,X_test.shape

((623, 7), (268, 7))

In [62]:
X_train=X_train.values
y_train=y_train.values
X_test=X_test.values
y_test=y_test.values

In [63]:
X_train=X_train.T
y_train=y_train.reshape(1,X_train.shape[1])

X_test=X_test.T
y_test=y_test.reshape(1,X_test.shape[1])

In [54]:
# defining sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [70]:
def model(X,Y,learning_rate,iterations):
    m=X_train.shape[1] #m is the number of observations
    n=X_train.shape[0] #n is the number of features

    W=np.zeros((n,1))
    B=0

    cost_list=[]
    for i in range(iterations):
        Z=np.dot(W.T,X)+B
        A=sigmoid(Z)

    #cost function
    cost=(-1/m)*np.sum(Y*np.log(A)+(1-Y)*np.log(1-A))

    #gradient descent
    dW=(1/m)*np.dot(A-Y,X.T)
    dB=(1/m)*np.sum(A-Y)

    W=W-learning_rate*dW.T
    B=W-learning_rate*dB

    cost_list.append(cost)
    if ((i%iterations)/10==0):
        print("cost after",i,"iteration is",cost)

    return W,B


model(X_train,y_train,0.005,100000)
    
        

(array([[-0.00213082],
        [-0.00103933],
        [-0.02602327],
        [-0.00039326],
        [-0.00013242],
        [ 0.01102261],
        [-0.00130417]]),
 array([[-0.00276083],
        [-0.00166934],
        [-0.02665329],
        [-0.00102327],
        [-0.00076244],
        [ 0.01039259],
        [-0.00193419]]))

In [ ]:
model(X_test)

## Another Implementation

In [20]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split

In [21]:
ir=load_iris()
X_train,X_test,y_train,y_test=train_test_split(ir.data,ir.target,random_state=100,test_size=0.3)

In [22]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [72]:
import numpy as np


class LogisticRegression:
    def __init__(self, learning_rate, iterations):
        self.learning_rate = learning_rate
        self.iterations = iterations
        self.W = None
        self.B = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        
        self.W = np.zeros(n_features)
        self.B = 0


        for i in range(self.iterations):
            linear_model = np.dot(X, self.W) + self.B
            y_predicted = self.sigmoid(linear_model)

            
            dW = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            dB = (1 / n_samples) * np.sum(y_predicted - y)
          
            self.W -= self.learning_rate * dW
            self.W -= self.learning_rate * dB

    def predict(self, X):
        linear_model = np.dot(X, self.W) + self.B
        y_predicted = self.sigmoid(linear_model)
        y_predicted_cls = [1 if i > 0.5 else 0 for i in y_predicted]
        return np.array(y_predicted_cls)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))


In [73]:
regressor=LogisticRegression(learning_rate=0.0005,iterations=10000)
regressor.fit(X_train,y_train)

In [74]:
y_pred=regressor.predict(X_test)

In [75]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.24444444444444444

In [76]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()

In [77]:
regression.fit(X_train,y_train)

LinearRegression()

In [78]:
y__pred=regression.predict(X_test)

In [80]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNe